import Head from 'next/head'
import { useState } from 'react';
import { useRouter } from 'next/router';
import Users from '@/components/Home/Users';

import InputForm from '@/components/Forms/InputForm'

export default function Home({users}) {
 
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Users data={heros} />
    </>
  )
}

export async function getServerSideProps(context) {
  const res = await fetch('http://localhost:3000/api/users')
  const data = await res.json()
  console.log(data)

  return {
    props: {data}, // will be passed to the page component as props
  }
}

