import Head from 'next/head'
import { useState } from 'react';
import { useRouter } from 'next/router';

import InputForm from '@/components/Forms/InputForm'

export default function Home() {
  const handleChange = (e) => {

  }

  const handleForm = (e) => {

  }



  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <table className="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">First</th>
            <th scope="col">Last</th>
            <th scope="col">Handle</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row">1</th>
            <td>Mark</td>
            <td>Otto</td>
            <td>@mdo</td>
          </tr>
        </tbody>  
        </table>
      </div>
      
      
    </>
  )
}
