import Head from 'next/head'
import { useState } from 'react';
import { useRouter } from 'next/router';

import Users from '@/components/Home/Users';
import InputForm from '@/components/Forms/InputForm'

export default function Home({users}) {
 //console.log(users)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Users data={users} />
    </>
  )
}

export async function getServerSideProps() {
  console.log('testing')

  let userData = []
  const res = await fetch('http://localhost:3000/api/users')
                .then( (result) => result.json())
                .then( responseData => userData = [...responseData])      
  //console.log('the api user response is', res)


  //const { user } = res.data
  //let data = JSON.parse(res)

  //console.log('users', data.users)
  //const  { users } = data.users
  //console.log('user type is', typeof(userData))
  //console.log('response is', res)
 
  //console.log('response is', userData.length)
  return {
    props: {users: res } // will be passed to the page component as props
  }
}

