import Head from 'next/head'
import { useState } from 'react';
import { useRouter } from 'next/router';

import InputForm from '@/components/Forms/InputForm'

export default function Home() {
    const [myThread, setMyThread] = useState( {title: "", message: ""});
    const [form, setForm] = useState( { firstname: "", lastname: "", profession: "" })

    const handleChange = (e) => {
        e.preventDefault();

        // let newThread =  ({ ...myThread, [id] : value})
        // setMyThread(newThread)


    }

    const handleForm = (e) => {
    
    }



  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <main className={styles.main}>
        <div className={styles.description}>
        </div>
      </main> */}
      <InputForm 
        onSubmit={handleForm}
        handleChange={handleChange}
        heading="Add a new User"
      />
      
    </>
  )
}
